import { readFile } from "node:fs/promises";
import path from "node:path";
import { NODE_TEMPLATE_FIELD_SPECS } from "./node-template-fields";
import {
  INLINE_NODE_FIELD,
  resolveAuthoredNodeFileReference,
  resolveWorkflowRelativeNodeFilePath,
} from "./authored-node";
import { resolveWorkflowRelativePath } from "./prompt-template-file";
import { err, ok, type Result } from "./result";
import {
  isSafeWorkflowName,
  resolveEffectiveRoots,
  resolveWorkflowScopedPath,
} from "./paths";
import { validateWorkflowBundle } from "./validate";
import type {
  LoadOptions,
  NormalizedWorkflowBundle,
  ValidationIssue,
} from "./types";

export interface LoadedWorkflow {
  readonly workflowName: string;
  readonly workflowDirectory: string;
  readonly artifactWorkflowRoot: string;
  readonly bundle: NormalizedWorkflowBundle;
}

export interface LoadFailure {
  readonly code: "INVALID_WORKFLOW_NAME" | "NOT_FOUND" | "IO" | "VALIDATION";
  readonly message: string;
  readonly issues?: readonly ValidationIssue[];
}

async function readJsonFile(
  filePath: string,
): Promise<Result<unknown, LoadFailure>> {
  try {
    const raw = await readFile(filePath, "utf8");
    return ok(JSON.parse(raw) as unknown);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "unknown error";
    if (message.includes("ENOENT")) {
      return err({
        code: "NOT_FOUND",
        message: `required file was not found: ${filePath}`,
      });
    }
    return err({
      code: "IO",
      message: `failed reading JSON file '${filePath}': ${message}`,
    });
  }
}

async function readTextFile(
  filePath: string,
): Promise<Result<string, LoadFailure>> {
  try {
    return ok(await readFile(filePath, "utf8"));
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "unknown error";
    if (message.includes("ENOENT")) {
      return err({
        code: "NOT_FOUND",
        message: `required file was not found: ${filePath}`,
      });
    }
    return err({
      code: "IO",
      message: `failed reading text file '${filePath}': ${message}`,
    });
  }
}

async function resolvePromptTemplateFileForNode(input: {
  readonly workflowDirectory: string;
  readonly nodeFile: string;
  readonly rawPayload: unknown;
}): Promise<Result<unknown, LoadFailure>> {
  if (typeof input.rawPayload !== "object" || input.rawPayload === null) {
    return ok(input.rawPayload);
  }

  const payload = input.rawPayload as Record<string, unknown>;
  const resolvedPayload: Record<string, unknown> = { ...payload };
  for (const spec of NODE_TEMPLATE_FIELD_SPECS) {
    const templateFile = payload[spec.fileField];
    if (typeof templateFile !== "string" || templateFile.length === 0) {
      continue;
    }

    const resolvedPath = resolveWorkflowRelativePath(
      input.workflowDirectory,
      templateFile,
    );
    if (!resolvedPath.ok) {
      return err({
        code: "IO",
        message: resolvedPath.error.message,
      });
    }

    const promptText = await readTextFile(resolvedPath.value);
    if (!promptText.ok) {
      return err({
        code: promptText.error.code,
        message:
          `failed resolving ${spec.fileField} for '${input.nodeFile}': ${promptText.error.message}`,
      });
    }

    resolvedPayload[spec.textField] = promptText.value;
  }

  return ok(resolvedPayload);
}

function buildDefaultWorkflowVis(
  workflowRaw: unknown,
): Result<unknown, LoadFailure> {
  if (
    typeof workflowRaw !== "object" ||
    workflowRaw === null ||
    !Array.isArray((workflowRaw as { nodes?: unknown }).nodes)
  ) {
    return err({
      code: "VALIDATION",
      message: "workflow.json is missing nodes[]",
      issues: [
        {
          severity: "error",
          path: "workflow.nodes",
          message: "must be an array",
        },
      ],
    });
  }

  const nodesRaw = (workflowRaw as { nodes: Array<{ id?: unknown }> }).nodes;
  return ok({
    nodes: nodesRaw
      .filter(
        (node): node is { id: string } =>
          typeof node.id === "string" && node.id.length > 0,
      )
      .map((node, order) => ({
        id: node.id,
        order,
      })),
    uiMeta: {
      layout: "vertical",
      autoGenerated: true,
    },
  });
}

export async function loadWorkflowFromDisk(
  workflowName: string,
  options: LoadOptions = {},
): Promise<Result<LoadedWorkflow, LoadFailure>> {
  if (!isSafeWorkflowName(workflowName)) {
    return err({
      code: "INVALID_WORKFLOW_NAME",
      message: `invalid workflow name '${workflowName}'`,
    });
  }

  const roots = resolveEffectiveRoots(options);
  const workflowDirectory = path.join(roots.workflowRoot, workflowName);

  const workflowPath = path.join(workflowDirectory, "workflow.json");
  const workflowVisPath = path.join(workflowDirectory, "workflow-vis.json");

  const workflowRaw = await readJsonFile(workflowPath);
  if (!workflowRaw.ok) {
    return err(workflowRaw.error);
  }

  const workflowVisRaw = await readJsonFile(workflowVisPath);
  const effectiveWorkflowVisRaw = workflowVisRaw.ok
    ? workflowVisRaw
    : workflowVisRaw.error.code === "NOT_FOUND"
      ? buildDefaultWorkflowVis(workflowRaw.value)
      : workflowVisRaw;

  if (!effectiveWorkflowVisRaw.ok) {
    return err(effectiveWorkflowVisRaw.error);
  }

  if (
    typeof workflowRaw.value !== "object" ||
    workflowRaw.value === null ||
    !Array.isArray((workflowRaw.value as { nodes?: unknown }).nodes)
  ) {
    return err({
      code: "VALIDATION",
      message: "workflow.json is missing nodes[]",
      issues: [
        {
          severity: "error",
          path: "workflow.nodes",
          message: "must be an array",
        },
      ],
    });
  }

  const workflowNodes = (
    workflowRaw.value as { nodes: Array<Record<string, unknown>> }
  ).nodes;
  const nodePayloads: Record<string, unknown> = {};

  for (const [index, node] of workflowNodes.entries()) {
    const nodeFile = resolveAuthoredNodeFileReference(node);
    if (nodeFile === undefined) {
      continue;
    }

    const inlineNodePayload = node[INLINE_NODE_FIELD];
    let rawPayload: unknown;
    if (typeof node["nodeFile"] === "string") {
      const nodeFilePath = resolveWorkflowRelativeNodeFilePath(
        workflowDirectory,
        nodeFile,
      );
      if (!nodeFilePath.ok) {
        return err({
          code: "VALIDATION",
          message: "workflow validation failed",
          issues: [
            {
              severity: "error",
              path: `workflow.nodes[${index}].nodeFile`,
              message: nodeFilePath.error.message,
            },
          ],
        });
      }
      const nodeRaw = await readJsonFile(nodeFilePath.value);
      if (!nodeRaw.ok) {
        return err(nodeRaw.error);
      }
      rawPayload = nodeRaw.value;
    } else {
      rawPayload = inlineNodePayload;
    }

    const resolvedNodeRaw = await resolvePromptTemplateFileForNode({
      workflowDirectory,
      nodeFile,
      rawPayload,
    });
    if (!resolvedNodeRaw.ok) {
      return err(resolvedNodeRaw.error);
    }
    nodePayloads[nodeFile] = resolvedNodeRaw.value;
  }

  const validation = validateWorkflowBundle({
    workflow: workflowRaw.value,
    workflowVis: effectiveWorkflowVisRaw.value,
    nodePayloads,
  });

  if (!validation.ok) {
    return err({
      code: "VALIDATION",
      message: "workflow validation failed",
      issues: validation.error,
    });
  }

  const artifactWorkflowRoot = resolveWorkflowScopedPath(
    roots.artifactRoot,
    validation.value.workflow.workflowId,
  );
  if (artifactWorkflowRoot === undefined) {
    return err({
      code: "VALIDATION",
      message: "workflow validation failed",
      issues: [
        {
          severity: "error",
          path: "workflow.workflowId",
          message:
            "must start with an alphanumeric character and contain only letters, digits, hyphens, or underscores",
        },
      ],
    });
  }

  return ok({
    workflowName,
    workflowDirectory,
    artifactWorkflowRoot,
    bundle: validation.value,
  });
}
